# Generated by Django 3.2.9 on 2021-12-01 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_item_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Список предпочтений', 'verbose_name_plural': 'Списки предпочтений'},
        ),
        migrations.RemoveField(
            model_name='trade',
            name='description',
        ),
        migrations.AddField(
            model_name='trade',
            name='currenc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.currency'),
        ),
    ]
