# Generated by Django 3.2.9 on 2021-12-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20211203_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='name',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='offer.stockbase'),
        ),
    ]
