# Generated by Django 3.2.9 on 2021-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_currency_course_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='course_sales',
        ),
        migrations.AddField(
            model_name='currency',
            name='course',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
