version: '3.3'
volumes:
  postgres_data:

services:
  web:
    build: ../trading
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../trading:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_docker
      - POSTGRES_PASSWORD=postgres_docker
      - POSTGRES_DB=postgres_docker_dev

  celery:
    build: ../trading
    command: celery -A trading worker -B --loglevel=info --logfile=logs/celery.log
    volumes:
      - ../trading:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ../trading
    command:  flower -A trading --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
      - celery
